// Code generated by ottplay-unification; DO NOT EDIT.
// Wire schema v1 SHA-256: 23a19dae2cb07334edadb2cb938749303dd44f0e81ad205352aa2a049c5b6ca4
package wire

const (
	CommandPath              = "/api/webhook/commands"
	AckPath                  = "/api/webhook/commands/ack"
	LegacyPollPath           = "/webhook/poll"
	LegacyNotifyPath         = "/webhook/notify"
	DeviceIdPattern          = "^[A-Za-z0-9._:-]{1,128}$"
	TokenPattern             = "^[A-Za-z0-9_-]{32,256}$"
	ServerCommandIdPattern   = "^[0-9a-f]{32}$"
	ClientCommandIdPattern   = "^[A-Za-z0-9_-]{1,128}$"
	AckBatchMax              = 50
	CommandEnvelopeMax       = 256
	SwopClientIdPattern      = "^[A-Za-z0-9._:-]{8,128}$"
	SwopClientHeader         = "X-Swop-Client-Id"
	SwopFallbackClientHeader = "X-Ottplay-Client-Id"
	SwopSessionPath          = "/session"
	SwopSubmitPath           = "/submit"
	SwopValuePath            = "/val"
	SwopDefaultTtl           = 600
	SwopCodeAlphabet         = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
	SwopCodeLength           = 6
	SwopCaptionLimit         = 200
	SwopDraftLimit           = 4000
	SwopValueLimit           = 8000
	SwopNoteLimit            = 200
)
