// Code generated by ottplay-unification; DO NOT EDIT.
// Wire schema v1 SHA-256: 23a19dae2cb07334edadb2cb938749303dd44f0e81ad205352aa2a049c5b6ca4
package control

import (
	"encoding/json"
	"errors"
	"math"
)

type wireField struct {
	kind             string
	minimum, maximum float64
	maxBytes         int
	primitive        string
}

var wireFields = map[string]wireField{
	"popup_duration":    {"number", 0.001, 3600, 0, ""},
	"channel_number":    {"integer", 1, 9007199254740991, 0, ""},
	"provider":          {"integer", 0, 9007199254740991, 0, ""},
	"volume":            {"number", 0, 100, 0, ""},
	"volume_step":       {"number", -math.MaxFloat64, math.MaxFloat64, 0, ""},
	"random_range":      {"range", 1, 9007199254740991, 0, ""},
	"channel_name":      {"text", -math.MaxFloat64, math.MaxFloat64, 1024, ""},
	"message":           {"text", -math.MaxFloat64, math.MaxFloat64, 8192, ""},
	"playlist":          {"text", -math.MaxFloat64, math.MaxFloat64, 8192, "httpUrl"},
	"provider_settings": {"text", -math.MaxFloat64, math.MaxFloat64, 8192, "json"},
}

type wireCommand struct{ required, optional, exactlyOne []string }

var wireCommands = map[string]wireCommand{
	"popup_message":            {[]string{"message"}, []string{"popup_duration"}, []string{}},
	"channel_by_number":        {[]string{"channel_number"}, []string{}, []string{}},
	"channel_by_name":          {[]string{"channel_name"}, []string{}, []string{}},
	"random_channel":           {[]string{}, []string{"random_range"}, []string{}},
	"change_provider":          {[]string{"provider"}, []string{}, []string{}},
	"change_provider_settings": {[]string{"provider_settings"}, []string{}, []string{}},
	"change_playlist":          {[]string{"playlist"}, []string{}, []string{}},
	"set_volume":               {[]string{}, []string{"volume", "volume_step"}, []string{"volume", "volume_step"}},
	"exit_player":              {[]string{}, []string{}, []string{}},
}

func validWireField(v json.RawMessage, rule wireField) bool {
	switch rule.kind {
	case "number", "integer":
		return numberValue(v, rule.minimum, rule.maximum, rule.kind == "integer")
	case "text":
		value, ok := textValue(v, rule.maxBytes)
		if !ok {
			return false
		}
		switch rule.primitive {
		case "json":
			return json.Valid([]byte(value))
		case "httpUrl":
			return wireHTTPURL(value)
		}
		return true
	case "range":
		var values []json.RawMessage
		if json.Unmarshal(v, &values) != nil || len(values) != 2 || !numberValue(values[0], rule.minimum, rule.maximum, true) || !numberValue(values[1], rule.minimum, rule.maximum, true) {
			return false
		}
		var lo, hi float64
		_ = json.Unmarshal(values[0], &lo)
		_ = json.Unmarshal(values[1], &hi)
		return lo <= hi
	}
	return false
}
func validateCommand(body []byte) (map[string]json.RawMessage, error) {
	m, err := decodeObject(body)
	if err != nil {
		return nil, err
	}
	cmd, ok := textValue(m["command"], 64)
	if !ok {
		return nil, errors.New("command is required")
	}
	policy, ok := wireCommands[cmd]
	if !ok {
		return nil, errors.New("unsupported command")
	}
	allowed := map[string]bool{"command": true}
	valid := true
	for _, key := range policy.required {
		allowed[key] = true
		valid = validWireField(m[key], wireFields[key]) && valid
	}
	for _, key := range policy.optional {
		allowed[key] = true
		if value, exists := m[key]; exists {
			valid = validWireField(value, wireFields[key]) && valid
		}
	}
	if len(policy.exactlyOne) > 0 {
		count := 0
		for _, key := range policy.exactlyOne {
			if _, exists := m[key]; exists {
				count++
			}
		}
		valid = valid && count == 1
	}
	for key := range m {
		if !allowed[key] {
			return nil, errors.New("unexpected command field")
		}
	}
	if !valid {
		return nil, errors.New("invalid command value")
	}
	return m, nil
}
